# Generated by Django 4.2.20 on 2025-03-16 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainer_auth', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainer',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='username',
            field=models.CharField(max_length=150, unique=True),
        ),
    ]
