# Generated by Django 4.2.20 on 2025-03-23 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainer_auth', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainer',
            name='expertise',
            field=models.CharField(default='body-building', max_length=100),
        ),
    ]
