# Generated by Django 5.1.6 on 2025-04-03 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='usertype',
            field=models.CharField(choices=[('trainee', 'Trainee'), ('trainer', 'Trainer')], default='trainee', max_length=10),
        ),
    ]
