# Generated by Django 5.1.6 on 2025-03-24 10:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('client_auth', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.FloatField(help_text='Current weight in kg')),
                ('height', models.FloatField(help_text='Height in cm')),
                ('goal_weight', models.FloatField(blank=True, help_text='Target weight in kg', null=True)),
                ('goal', models.CharField(choices=[('lose_weight', 'Lose Weight'), ('gain_muscle', 'Gain Muscle'), ('stay_fit', 'Stay Fit')], help_text='Overall fitness goal', max_length=20)),
                ('workout_room', models.CharField(choices=[('gym', 'Gym'), ('home', 'Home'), ('outdoor', 'Outdoor')], help_text='Where you prefer to work out', max_length=10)),
                ('workout_time', models.CharField(help_text='Preferred workout time (e.g., Morning, Evening, etc.)', max_length=50)),
                ('illness', models.TextField(blank=True, help_text='Any illnesses or medical conditions', null=True)),
                ('workout_experience', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], help_text='Workout experience level', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('trainee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tests', to='client_auth.trainee')),
            ],
        ),
    ]
